# Generated by Django 4.0 on 2022-02-15 05:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_alter_item_tags'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0009_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemClone',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.tag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemOwnerClone', to='auth.user')),
            ],
        ),
    ]
