# Generated by Django 4.0 on 2022-02-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_alter_item_tags'),
        ('user', '0011_itemclone_id_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemclone',
            name='sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.sheet'),
        ),
    ]
